# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Pi Link'
tagline:          'A Metro theme for Jekyll'
description:      'A Sample blog using Jekyll Metro'
url:              ''
baseurl:          ''
port:    '8085'


# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Safouen Ferchichi'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       '#'
flickr:
github:         'https://github.com/pilink'
gplus:          '#'
instagram:
pinterest:
linkedin:       'https://fr.linkedin.com/in/safouen-ferchichi-44186060'
rss:
stackoverflow:  'http://stackoverflow.com/users/5684272/safouen-ferchichi'
twitter:        '#'

# Google Analytics
gahandler: 'UA-52149651-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2

# Gems
gems: [jekyll-paginate]
