# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'veoPi'
tagline:          'A Metro theme for Jekyll'
description:      'veoPi'
url:              ''
baseurl:          ''
port:    '4000'


# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Safouen Ferchichi'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com/veopi/'
flickr:
github:         'https://github.com/veopi'
gplus:          '#'
instagram:      'https://www.instagram.com/veopi/'
pinterest:
linkedin:       'https://fr.linkedin.com/in/safouen-ferchichi-44186060'
rss:
stackoverflow:  'http://stackoverflow.com/users/5684272/safouen-ferchichi'
twitter:        'https://twitter.com/veo_pi'

# Google Analytics
gahandler: 'UA-89712528-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'veopi'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2

# Gems
gems: [jekyll-paginate]
